spring.application.name=anti-thief

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=false

spring.flyway.enabled=${FLYWAY_ENABLED:false}

app.security.aes-key=${AES_KEY}
app.security.api-key=${API_KEY}
app.security.map-username=${MAP_USERNAME}
app.security.map-password=${MAP_PASSWORD}

spring.servlet.multipart.max-request-size=1MB
spring.servlet.multipart.max-file-size=1MB
